 nombre: Configurar el entorno Node.js
  usos: acciones/setup-node@v4.0.2
  con:
    # Establecer autenticaci√≥n siempre en npmrc.
    autenticaci√≥n siempre: # opcional, el valor predeterminado es falso
    # Versi√≥n Especificaci√≥n de la versi√≥n a utilizar. Ejemplos: 12.x, 10.15.1, >=10.15.0.
    versi√≥n-nodo: # opcional
    # Archivo que contiene la versi√≥n Spec de la versi√≥n a utilizar. Ejemplos: paquete.json, .nvmrc, .node-version, .tool-versions.
    archivo-versi√≥n-nodo: # opcional
    # Arquitectura de destino para que la utilice Node. Ejemplos: x86, x64. Utilizar√° la arquitectura del sistema de forma predeterminada.
    arquitectura: # opcional
    # Configure esta opci√≥n si desea que la acci√≥n busque la √∫ltima versi√≥n disponible que satisfaga la especificaci√≥n de versi√≥n.
    comprobar lo √∫ltimo: # opcional
    # Registro opcional para configurar para la autenticaci√≥n. Configurar√° el registro en un archivo .npmrc y .yarnrc a nivel de proyecto, y configurar√° la autenticaci√≥n para leer desde env.NODE_AUTH_TOKEN.
    URL de registro: # opcional
    # Alcance opcional para la autenticaci√≥n en registros con alcance. Recurrir√° al propietario del repositorio cuando se utilice el registro de paquetes de GitHub (https://npm.pkg.github.com/).
    alcance: # opcional
    # Se utiliza para extraer distribuciones de nodos de versiones de nodos. Dado que existe un valor predeterminado, normalmente el usuario no lo proporciona. Al ejecutar esta acci√≥n en github.com, el valor predeterminado es suficiente. Cuando se ejecuta en GHES, puede pasar un token de acceso personal para github.com si experimenta una limitaci√≥n de velocidad.
    token: # opcional, el valor predeterminado es ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Se utiliza para especificar un administrador de paquetes para el almacenamiento en cach√© en el directorio predeterminado. Valores admitidos: npm, hilo, pnpm.
    cach√©: # opcional
    # Se utiliza para especificar la ruta a un archivo de dependencia: package-lock.json, Yarn.lock, etc. Admite comodines o una lista de nombres de archivos para almacenar en cach√© m√∫ltiples dependencias.
    ruta-dependencia-cach√©: # opcional

                  - name: OpenCommit ‚Äî improve commits with AI üßô
                uses: di-sukharev/opencommit@github-action-v1.0.2
            
    
          
